/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JOptionPane;

/**
 *
 * @author kisha
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form currency
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtFrom = new javax.swing.JComboBox<>();
        txtTo = new javax.swing.JComboBox<>();
        Convert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField1.setText("          Currency Converter");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Enter the Amount");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("To");

        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        txtFrom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "Euro", "British Pound", "Australian Dollar", "Singapore Dollar", "Japanese Yen", "Swiss France", "Indian Rupee" }));
        txtFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromActionPerformed(evt);
            }
        });

        txtTo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian Rupee", "USD", "Euro", "British Pound", "Australian Dollar", "Singapore Dollar", "Japanese Yen", "Swiss France", " ", " " }));
        txtTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToActionPerformed(evt);
            }
        });

        Convert.setBackground(new java.awt.Color(204, 204, 255));
        Convert.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Convert.setText("Convert");
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAmount)
                            .addComponent(txtFrom, 0, 204, Short.MAX_VALUE)
                            .addComponent(txtTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtFromActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtToActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {                                        
Double convert;
        Double amount=Double.parseDouble(txtAmount.getText());
if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="Indian Rupee")
    
{
    convert=amount*81.99;
    JOptionPane.showMessageDialog(this,"The Amount is : Rs "+convert.toString());
    
}

else if(txtFrom.getSelectedItem().toString()=="Euro" && txtTo.getSelectedItem().toString()=="Indian Rupee")
    
{
    convert=amount*89.64;
    JOptionPane.showMessageDialog(this,"The Amount is : Rs "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="British Pound" && txtTo.getSelectedItem().toString()=="Indian Rupee")
    
{
    convert=amount*104.24;
    JOptionPane.showMessageDialog(this,"The Amount is : Rs "+convert.toString());
    
}

else if(txtFrom.getSelectedItem().toString()=="Australian Dollar" && txtTo.getSelectedItem().toString()=="Indian Rupee")
    
{
    convert=amount*54.86;
    JOptionPane.showMessageDialog(this,"The Amount is : Rs "+convert.toString());
    
}


else if(txtFrom.getSelectedItem().toString()=="Singapore Dollar" && txtTo.getSelectedItem().toString()=="Indian Rupee")
    
{
    convert=amount*60.65;
    JOptionPane.showMessageDialog(this,"The Amount is : Rs "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="Swiss France" && txtTo.getSelectedItem().toString()=="Indian Rupee")
    
{
    convert=amount*91.43;
    JOptionPane.showMessageDialog(this,"The Amount is : Rs "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="Japanese Yen" && txtTo.getSelectedItem().toString()=="Indian Rupee")
    
{
    convert=amount*0.57;
    JOptionPane.showMessageDialog(this,"The Amount is : Rs "+convert.toString());
    
}

else if(txtFrom.getSelectedItem().toString()=="Indian Rupee" && txtTo.getSelectedItem().toString()=="USD")
    
{
    convert=amount*0.012;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}

else if(txtFrom.getSelectedItem().toString()=="Indian Rupee" && txtTo.getSelectedItem().toString()=="Euro")
    
{
    convert=amount*0.011;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="Indian Rupee" && txtTo.getSelectedItem().toString()=="British Pound")
    
{
    convert=amount*0.0096;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
   
}

else if(txtFrom.getSelectedItem().toString()=="Indian Rupee" && txtTo.getSelectedItem().toString()=="Australian Dollar")
    
{
    convert=amount*0.018;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}


else if(txtFrom.getSelectedItem().toString()=="Indian Rupee" && txtTo.getSelectedItem().toString()=="Singapore Dollar")
    
{
    convert=amount*0.016;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="Indian Rupee" && txtTo.getSelectedItem().toString()=="Swiss France")
    
{
    convert=amount*0.011;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="Indian Rupee" && txtTo.getSelectedItem().toString()=="Japanese Yen")
    
{
    convert=amount*1.76;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}

//********************************** ************************************





else if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="British Pound")
    
{
    convert=amount*0.79;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="British Pound" && txtTo.getSelectedItem().toString()=="USD")
    
{
    convert=amount*1.26;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}













else if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="Euro")
    
{
    convert=amount*0.92;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="Euro" && txtTo.getSelectedItem().toString()=="USD")
    
{
    convert=amount*1.09;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="Euro" && txtTo.getSelectedItem().toString()=="British Pound")
    
{
    convert=amount*0.86;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="British Pound" && txtTo.getSelectedItem().toString()=="Euro")
    
{
    convert=amount*1.16;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}

else if(txtFrom.getSelectedItem().toString()=="British Pound" && txtTo.getSelectedItem().toString()=="Australian Dollar")
    
{
    convert=amount*1.91;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}


else if(txtFrom.getSelectedItem().toString()=="Australian Dollar" && txtTo.getSelectedItem().toString()=="British Pound")
    
{
    convert=amount*0.52;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}






else if(txtFrom.getSelectedItem().toString()=="Australian Dollar" && txtTo.getSelectedItem().toString()=="Singapore Dollar")
    
{
    convert=amount*0.52;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}

else if(txtFrom.getSelectedItem().toString()=="Singapore Dollar" && txtTo.getSelectedItem().toString()=="Australian Dollar")
    
{
    convert=amount*1.12;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}



else if(txtFrom.getSelectedItem().toString()=="Singapore Dollar" && txtTo.getSelectedItem().toString()=="Japanese Yen")
    
{
    convert=amount*106.65;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}


else if(txtFrom.getSelectedItem().toString()=="Japanese Yen" && txtTo.getSelectedItem().toString()=="Singapore Dollar")
    
{
    convert=amount*0.0094;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}


else if(txtFrom.getSelectedItem().toString()=="Japanese Yen" && txtTo.getSelectedItem().toString()=="Swiss France")
    
{
    convert=amount*0.0062;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}
else if(txtFrom.getSelectedItem().toString()=="Swiss France" && txtTo.getSelectedItem().toString()=="Japanese Yen")
    
{
    convert=amount*1;
    JOptionPane.showMessageDialog(this,"The Amount is :  "+convert.toString());
    
}



































        // TODO add your handling code here:
    }                                       

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Convert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JComboBox<String> txtFrom;
    private javax.swing.JComboBox<String> txtTo;
    // End of variables declaration                   
}
